config/routes.rb
Todoodly::Application.routes.draw do

  devise_for :users

  resources :lists do
    resources :tasks
  end

  match 'lists/:list_id/tasks/:id/complete', :to => 'tasks#complete', :as => :complete_task

  root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, :presence => true

  has_many :tasks 
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :description, :list_id

  validates :description, :presence => true

  belongs_to :list

  scope :completed, where(:completed => true)
  scope :incomplete, where(:completed => false)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	before_filter :authenticate_user!, except: :index

	respond_to :html, :xml, :js

	def index
		if user_signed_in?
			@lists = current_user.lists.all
		end
	end

	def new
		@list = current_user.lists.new
	end

	def create
		@list = current_user.lists.new(params[:list])
		if @list.save
			flash[:success] = "List created!"
			redirect_to list_path(@list)
		else
			flash[:error] = "Shit, could not create list"
			redirect_to new_list_path
		end
	end

	def show
		@list = current_user.lists.find(params[:id])
	end

	def edit
		@list = current_user.lists.find(params[:id])
	end

	def update
		@list = current_user.lists.find(params[:id])
		if @list.update_attributes(params[:list])
			flash[:success] = "List updated."
			redirect_to list_path(@list)
		else
			flash[:error] = "List did not update :("
			redirect_to edit_list_path(@list)
		end
	end

	def destroy
		@list = current_user.lists.find(params[:id])
		if @list.destroy
			flash[:success] = "List deleted!"
			redirect_to lists_path
		else
			flash[:error] = "Could not delete."
			redirect_to lists_path
		end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	attr_accessor :completed
	before_filter :find_list, :authenticate_user!
	respond_to :html, :xml, :js

	def create
		@task = @list.tasks.new(params[:task])
		if @task.save
			flash[:success] = "Woohoo! Task Created!"
			redirect_to list_path(@list)
		else
			flash[:error] = "Shit, could not create task!"
			redirect_to list_path(@list)
		end
	end

	def complete
		@task = @list.tasks.find(params[:id])
		@task.completed = true
		@task.save
		redirect_to list_path(@list)
	end

	private

	def find_list
		@list = current_user.lists.find(params[:list_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDooDoo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
        <div class="brand"><%= link_to "ToDooDoo", root_path, id: "logo" %></div>
      <div class="nav-collapse">
      	<ul class="nav pull-right">
          <% if user_signed_in? %>
      		  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
      </div>
		</div>
	</div>
</div>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% if user_signed_in? %>
    <div class="container">
      <div class="row">
        <div class="span3">
          <ul class="nav nav-list">
            <li class="nav-header">
              ToDoodles
            </li>
            <li <% if current_page?(lists_path) %>class="active"<% end %>>
              <%= link_to "<i class='icon-home'></i> Home".html_safe, lists_path %>
            </li>
            <li <% if current_page?(new_list_path) %>class="active"<% end %>>
              <%= link_to "<i class='icon-plus-sign'></i> New list".html_safe, new_list_path %>
            </li>
            <li>
              <%= link_to "<i class='icon-tasks'></i> All tasks".html_safe, '#' %>
            </li>
            <li class="nav-header">
              Options
            </li>
            <li>
              <%= link_to "<i class='icon-flag'></i> Help".html_safe, '#' %>
            </li>
            <li>
              <%= link_to "<i class='icon-cog'></i> Settings".html_safe, '#' %>
            </li>
          </ul>
        </div>
        <div class="span9"><%= yield %></div>
      </div>
    </div>
  <% else %>
    <div class="container">
      <%= yield %>
    </div>
  <% end %>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |form| %>

	<label>Name:
		<p><%=form.text_field :name %></p>
	</label>

	<label>Description:
		<p><%=form.text_field :description %></p>
	</label>

	<p><%= form.submit %></p>

<% end %>

app/views/lists/edit.html.erb
<h1>Edit this list</h1>

<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<% if !user_signed_in? %>
	<div class="center hero-unit">
	<h1 id="herotext">Welcome to ToDooDoo</h1>
	</div>
<% else %>

<% @lists.each do |list| %>

	<h2><%= link_to list.name, list_path(list) %></h2>
	<p><%= list.description %> - <%= link_to "Edit", edit_list_path(list) %> | <%= link_to "Delete", list_path(list), :method => :delete %></p> 

<% end %>

<% end %>

app/views/lists/new.html.erb
<h1>New Todo List</h1>

<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<div class="page-header">
<h2><%= @list.name %></h2>
<h6><%= @list.description %></h6>
</div>

<h3>Shit to do</h3>
<ul>
	<% @list.tasks.incomplete.each do |task| %>
	<li><%= link_to "<i class='icon-ok'></i>".html_safe, complete_task_path(@list.id,task.id), class: "btn btn-mini btn-success" %>   <%= task.description %></li>
	<% end %>
</ul>
<br>
<h3>Completed shit</h3>
<ul>
	<% @list.tasks.completed.each do |task| %>
	<li><%= task.description %></li>
	<% end %>
</ul>



<%= form_for [@list, @task = @list.tasks.new] do |form| %>

<p><%= form.text_field :description %> <%= form.submit %></p>

<% end %>